import { NextRequest, NextResponse } from "next/server";

function esc(value: unknown) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function nl2br(s: string) {
  return esc(s).replaceAll("\n", "<br/>");
}

export async function POST(req: NextRequest) {
  try {
    const payload = await req.json();

    const customer = payload?.customer ?? {};
    const move = payload?.move ?? {};
    const pricing = payload?.pricing ?? {};
    const notesArr: unknown = payload?.notes;
    const notes = Array.isArray(notesArr) ? notesArr.map((n) => String(n ?? "")) : [];

    const html = `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Alto Moving — Estimate</title>
    <style>
      :root {
        --fg: #111;
        --muted: #666;
        --border: #ddd;
        --bg: #fff;
      }
      body {
        font-family: Arial, sans-serif;
        padding: 24px;
        color: var(--fg);
        background: var(--bg);
      }
      h1 { font-size: 20px; margin: 0 0 8px; }
      h2 { font-size: 16px; margin: 18px 0 6px; }
      table { width: 100%; border-collapse: collapse; margin: 8px 0; }
      td, th { border: 1px solid var(--border); padding: 8px; font-size: 13px; vertical-align: top; }
      small { color: var(--muted); }
      .top {
        display: flex;
        align-items: flex-start;
        justify-content: space-between;
        gap: 16px;
      }
      .actions {
        display: flex;
        gap: 10px;
      }
      .btn {
        border: 1px solid var(--border);
        background: #111;
        color: #fff;
        padding: 8px 10px;
        border-radius: 10px;
        font-size: 12px;
        cursor: pointer;
      }
      .btn.ghost {
        background: #fff;
        color: #111;
      }
      .notes {
        font-size: 13px;
        color: var(--muted);
        line-height: 1.5;
      }
      @media print {
        body { padding: 0; }
        .actions { display: none; }
      }
    </style>
  </head>
  <body>
    <div class="top">
      <div>
        <h1>Nonbinding Estimate — Tariff 15-C Compliant</h1>
        <small>Generated by Alto Moving. Final charges per actual services & conditions.</small>
      </div>
      <div class="actions">
        <button class="btn" onclick="window.print()">Print / Save as PDF</button>
        <button class="btn ghost" onclick="window.close()">Close</button>
      </div>
    </div>

    <h2>Customer</h2>
    <table>
      <tr><th>Name</th><td>${esc(customer.name)}</td></tr>
      <tr><th>Email</th><td>${esc(customer.email)}</td></tr>
      <tr><th>Phone</th><td>${esc(customer.phone)}</td></tr>
    </table>

    <h2>Move</h2>
    <table>
      <tr><th>Pickup ZIP</th><td>${esc(move.pickupZip)}</td></tr>
      <tr><th>Drop-off ZIP</th><td>${esc(move.dropoffZip)}</td></tr>
      <tr><th>Distance (mi)</th><td>${esc(move.distance)}</td></tr>
      <tr><th>Type</th><td>${esc(move.type)}</td></tr>
      <tr><th>Home Size</th><td>${esc(move.homeSize)}</td></tr>
      <tr><th>Crew / Trucks</th><td>${esc(move.crew)} / ${esc(move.trucks)}</td></tr>
      <tr><th>Packing</th><td>${move.packing ? "Included" : "No"}</td></tr>
      <tr><th>Access</th><td>${
        Array.isArray(move.access) && move.access.length ? esc(move.access.join(", ")) : ""
      }</td></tr>
    </table>

    <h2>Estimate</h2>
    <table>
      <tr><th>Billing</th><td>${esc(pricing.billing)}</td></tr>
      <tr><th>Filed Rate</th><td>${esc(pricing.filedRate)}</td></tr>
      <tr><th>Estimated Range</th><td>${esc(pricing.range)}</td></tr>
    </table>

    <h2>Notes</h2>
    <div class="notes">
      ${
        notes.length
          ? notes.map((n) => `<div>${nl2br(n)}</div>`).join("")
          : "<small>No additional notes.</small>"
      }
    </div>

    <p><small>Based on WA Tariff 15-C; Alto’s filed rates within tariff bands apply.</small></p>
  </body>
</html>
`.trim();

    return new NextResponse(html, {
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  } catch (e) {
    console.error(e);
    return NextResponse.json({ ok: false, error: "Server error" }, { status: 500 });
  }
}
